# THEY EXIST METHODS AND FUNCTIONS BUILT INTO PYTHON EG STRING METHODS ETC


#  AS A PROGRAMMER YOUR JOB IS NOT TO MEMORISE EVERYTHING BUT RATHER HAVE AS MANY RESOURCES AS POSSIBLE AND KNOW WHEN TO USE THEM



quote = 'to be or not to be '

print(quote.upper()) 